// src/pages/TermsOfUsePage.tsx

import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const TermsOfUsePage: React.FC = () => {
  const navigate = useNavigate();
  const effectiveDate = new Date().toISOString().split('T')[0];

  return (
    <div className="bg-slate-50 dark:bg-slate-900">
      <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
        <div className="max-w-4xl mx-auto text-slate-800 dark:text-slate-300">
          
          <div className="mb-8">
            <button
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-sky-500 dark:hover:text-sky-400 transition-colors"
              aria-label="Go back to previous page"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
          </div>

          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-slate-50 mb-4 text-center">
            Terms of Service
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-center mb-12">
            Last Updated: {effectiveDate}
          </p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 leading-relaxed">
            <p>
              Welcome to <strong>CodeNova</strong> (referred to as "we," "us," "our," or the "Platform"). These Terms of Service ("Terms") govern your access to and use of our online learning platform, curriculum, community forums, and all related services (collectively, the "Service").
            </p>
            <p>
              By creating an account, accessing, or using the Service, you agree to be bound by these Terms and our <Link to="/privacy">Privacy Policy</Link>. If you do not agree, you may not use the Service.
            </p>

            <h2 id="program">1. The Service</h2>
            <p>
              CodeNova provides a 6-month online program designed to teach web development skills, including but not limited to HTML, CSS, JavaScript, React, Node.js, and Next.js. The program is delivered online through video lessons, articles, projects, and community support.
            </p>

            <h2 id="accounts">2. User Accounts</h2>
            <p>
              To use most features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during registration and to keep this information updated. You are responsible for safeguarding your password and for all activities that occur under your account.
            </p>

            <h2 id="conduct">3. Code of Conduct</h2>
            <p>
              You agree to use the Service in a professional and respectful manner. You will not:
            </p>
            <ul>
              <li>Submit work that is not your own. Plagiarism or submitting code generated by AI tools as your own original work is strictly prohibited and may result in termination of your account.</li>
              <li>Harass, threaten, or defame any other user or staff member.</li>
              <li>Share your account credentials with any other person.</li>
              <li>Use the Service for any illegal or unauthorized purpose.</li>
            </ul>
            <p>
              Violation of this Code of Conduct may result in immediate suspension or termination of your access to the Service, without refund.
            </p>
            
            <h2 id="payments">4. Payments, Subscriptions, and Refunds</h2>
            <p>
              Access to certain features of the Service may require payment of fees. You agree to pay all applicable fees for the subscription plan you select. All fees are non-refundable, except as required by law or as otherwise stated at the time of purchase. We reserve the right to change our pricing and subscription plans at any time, and we will provide you with notice of any such changes.
            </p>

            <h2 id="ip">5. Intellectual Property</h2>
            <ul>
              <li>
                <strong>Our Content:</strong> All materials provided by CodeNova, including videos, text, code samples, and the structure of the curriculum, are the intellectual property of CodeNova or its licensors. We grant you a limited, non-exclusive, non-transferable license to access and use these materials for your personal, non-commercial educational purposes only.
              </li>
              <li>
                <strong>Your Content:</strong> You retain full ownership of the original code, projects, and other intellectual property you create while using the Service. By submitting your projects for review, you grant us a non-exclusive license to view and provide feedback on your work for educational purposes.
              </li>
            </ul>

            <h2 id="certification">6. Certification</h2>
            <p>
              Upon successful completion of the program requirements, you may be awarded a Certificate of Completion from CodeNova. This certificate is a recognition of your completion of the curriculum and does not represent an academic degree or any form of professional licensure.
            </p>

            <h2 id="disclaimers">7. Disclaimers and Limitation of Liability</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind. We do not guarantee that the Service will be uninterrupted or error-free. We do not guarantee employment or any specific career outcome as a result of completing the program.
            </p>
            <p>
              To the fullest extent permitted by law, CodeNova shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service.
            </p>

            <h2 id="termination">8. Termination</h2>
            <p>
              We may terminate or suspend your account at any time, without prior notice, for conduct that violates these Terms or for any other reason we deem necessary to protect the integrity of the Platform.
            </p>
            
            <h2 id="governing-law">9. Governing Law</h2>
            <p>
              <strong>[IMPORTANT]</strong> These Terms shall be governed by the laws of <strong>Ethiopia</strong>, without regard to its conflict of law provisions. You should replace the bracketed text with your actual legal jurisdiction.
            </p>

            <h2 id="changes">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify you of any material changes by posting the new Terms on the site and updating the "Last Updated" date.
            </p>

            <h2 id="contact">11. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at <a href="mailto:contact@codenova.com">contact@codenova.com</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfUsePage;